source 'http://rubygems.org'

gem 'activerecord', '6.1.7.3', :require => 'active_record'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'pry'
gem 'pry-nav'
gem 'rack-test', '>= 2.0.0'
gem 'rake', '>= 12.3.3'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra', '>= 2.2.3'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3'
gem 'thin'
gem 'tux'
gem 'capybara'
