source 'http://rubygems.org'

gem 'activerecord', '4.2.5', :require => 'active_record'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'pry'
gem 'pry-nav'
gem 'rack-test', '>= 2.0.0'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra', '>= 2.0.6'
gem 'sinatra-activerecord', '>= 2.0.14', :require => 'sinatra/activerecord'
gem 'sqlite3'
gem 'thin', '>= 1.8.0'
gem 'tux'
gem 'capybara', '>= 3.13.1'
